import pygame

TILE_SIZE = 32

GRID_WIDTH = 20
GRID_HEIGHT = 16

DISPLAY_WIDTH = TILE_SIZE * GRID_WIDTH
DISPLAY_HEIGHT = TILE_SIZE * GRID_HEIGHT
DISPLAY_FLAGS = pygame.SCALED | pygame.RESIZABLE

DISPLAY_TITLE = "A-Star Project"

WHITE, BLACK = pygame.Color(255, 255, 255, 255), pygame.Color(0, 0, 0, 0)

PLAYER_COLOR = pygame.Color(0, 128, 255, 255)

OBSTACLE_COLOR = pygame.Color(0, 0, 0, 255)
OBSTACLE_BLINK_COLOR = pygame.Color(255, 0, 0, 255)

OBSTACLE_PERCENT = 0.1
OBSTACLE_BLINK_DURATION = 0.1